-- 插入generic类型的角色数据
-- 基于权威身高数据和SVG文件，使用GitHub仓库URL

-- 清空现有generic角色数据（可选）
-- DELETE FROM characters WHERE type = 'generic';

-- 成年男性角色 (平均身高1.75米)
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('generic-man-1', 'Man 1', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man1.svg', '#3B82F6', false, 'fill'),
('generic-man-2', 'Man 2', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man2.svg', '#3B82F6', false, 'fill'),
('generic-man-3', 'Man 3', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man3.svg', '#3B82F6', false, 'fill'),
('generic-man-4', 'Man 4', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man4.svg', '#3B82F6', false, 'fill'),
('generic-man-5', 'Man 5', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man5.svg', '#3B82F6', false, 'fill'),
('generic-man-6', 'Man 6', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man6.svg', '#3B82F6', false, 'fill'),
('generic-man-7', 'Man 7', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man7.svg', '#3B82F6', false, 'fill'),
('generic-man-8', 'Man 8', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/man8.svg', '#3B82F6', false, 'fill');

-- 成年女性角色 (平均身高1.62米)  
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('woman-1', 'Woman 1', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman1.svg', '#EC4899', false, 'fill'),
('woman-2', 'Woman 2', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman2.svg', '#EC4899', false, 'fill'),
('woman-3', 'Woman 3', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman3.svg', '#EC4899', false, 'fill'),
('woman-4', 'Woman 4', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman4.svg', '#EC4899', false, 'fill'),
('woman-5', 'Woman 5', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman5.svg', '#EC4899', false, 'fill'),
('woman-6', 'Woman 6', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman6.svg', '#EC4899', false, 'fill'),
('woman-7', 'Woman 7', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/woman7.svg', '#EC4899', false, 'fill');

-- 12岁男孩角色 (平均身高1.50米)
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('boy-1', 'Boy 1', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy1.svg', '#10B981', false, 'fill'),
('boy-2', 'Boy 2', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy2.svg', '#10B981', false, 'fill'),
('boy-3', 'Boy 3', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy3.svg', '#10B981', false, 'fill'),
('boy-4', 'Boy 4', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy4.svg', '#10B981', false, 'fill'),
('boy-5', 'Boy 5', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy5.svg', '#10B981', false, 'fill'),
('boy-6', 'Boy 6', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy6.svg', '#10B981', false, 'fill'),
('boy-7', 'Boy 7', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy7.svg', '#10B981', false, 'fill'),
('boy-8', 'Boy 8', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy8.svg', '#10B981', false, 'fill'),
('boy-9', 'Boy 9', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy9.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy9.svg', '#10B981', false, 'fill'),
('boy-10', 'Boy 10', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy10.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy10.svg', '#10B981', false, 'fill'),
('boy-11', 'Boy 11', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy11.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy11.svg', '#10B981', false, 'fill'),
('boy-12', 'Boy 12', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy12.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy12.svg', '#10B981', false, 'fill'),
('boy-13', 'Boy 13', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy13.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy13.svg', '#10B981', false, 'fill'),
('boy-14', 'Boy 14', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy14.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy14.svg', '#10B981', false, 'fill'),
('boy-15', 'Boy 15', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy15.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy15.svg', '#10B981', false, 'fill'),
('boy-16', 'Boy 16', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy16.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy16.svg', '#10B981', false, 'fill'),
('boy-17', 'Boy 17', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy17.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy17.svg', '#10B981', false, 'fill'),
('boy-18', 'Boy 18', 1.50, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy18.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/boy18.svg', '#10B981', false, 'fill');

-- 12岁女孩角色 (平均身高1.51米)
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('girl-1', 'Girl 1', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl1.svg', '#F59E0B', false, 'fill'),
('girl-2', 'Girl 2', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl2.svg', '#F59E0B', false, 'fill'),
('girl-3', 'Girl 3', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl3.svg', '#F59E0B', false, 'fill'),
('girl-4', 'Girl 4', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl4.svg', '#F59E0B', false, 'fill'),
('girl-5', 'Girl 5', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl5.svg', '#F59E0B', false, 'fill'),
('girl-6', 'Girl 6', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl6.svg', '#F59E0B', false, 'fill'),
('girl-7', 'Girl 7', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl7.svg', '#F59E0B', false, 'fill'),
('girl-8', 'Girl 8', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl8.svg', '#F59E0B', false, 'fill'),
('girl-9', 'Girl 9', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl9.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl9.svg', '#F59E0B', false, 'fill'),
('girl-10', 'Girl 10', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl10.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl10.svg', '#F59E0B', false, 'fill'),
('girl-11', 'Girl 11', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl11.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl11.svg', '#F59E0B', false, 'fill'),
('girl-12', 'Girl 12', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl12.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl12.svg', '#F59E0B', false, 'fill'),
('girl-13', 'Girl 13', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl13.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl13.svg', '#F59E0B', false, 'fill'),
('girl-14', 'Girl 14', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl14.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl14.svg', '#F59E0B', false, 'fill'),
('girl-15', 'Girl 15', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl15.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl15.svg', '#F59E0B', false, 'fill'),
('girl-16', 'Girl 16', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl16.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl16.svg', '#F59E0B', false, 'fill'),
('girl-17', 'Girl 17', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl17.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl17.svg', '#F59E0B', false, 'fill'),
('girl-18', 'Girl 18', 1.51, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl18.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/girl18.svg', '#F59E0B', false, 'fill');

-- 老年男性角色 (平均身高1.68米)
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('oldman-1', 'Old Man 1', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman1.svg', '#6B7280', false, 'fill'),
('oldman-2', 'Old Man 2', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman2.svg', '#6B7280', false, 'fill'),
('oldman-3', 'Old Man 3', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman3.svg', '#6B7280', false, 'fill'),
('oldman-4', 'Old Man 4', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman4.svg', '#6B7280', false, 'fill'),
('oldman-5', 'Old Man 5', 1.68, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldman5.svg', '#6B7280', false, 'fill');

-- 老年女性角色 (平均身高1.58米)
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('oldwoman-1', 'Old Woman 1', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman1.svg', '#9CA3AF', false, 'fill'),
('oldwoman-2', 'Old Woman 2', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman2.svg', '#9CA3AF', false, 'fill'),
('oldwoman-3', 'Old Woman 3', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman3.svg', '#9CA3AF', false, 'fill'),
('oldwoman-4', 'Old Woman 4', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman4.svg', '#9CA3AF', false, 'fill'),
('oldwoman-5', 'Old Woman 5', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman5.svg', '#9CA3AF', false, 'fill'),
('oldwoman-6', 'Old Woman 6', 1.58, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/oldwoman6.svg', '#9CA3AF', false, 'fill');

-- 可自定义颜色的成年男性角色 (genman系列)
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('genman-1', 'Generic Man 1', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman1.svg', '#3B82F6', true, 'fill'),
('genman-2', 'Generic Man 2', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman2.svg', '#3B82F6', true, 'fill'),
('genman-3', 'Generic Man 3', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman3.svg', '#3B82F6', true, 'fill'),
('genman-4', 'Generic Man 4', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman4.svg', '#3B82F6', true, 'fill'),
('genman-5', 'Generic Man 5', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman5.svg', '#3B82F6', true, 'fill'),
('genman-6', 'Generic Man 6', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman6.svg', '#3B82F6', true, 'fill'),
('genman-7', 'Generic Man 7', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman7.svg', '#3B82F6', true, 'fill'),
('genman-8', 'Generic Man 8', 1.75, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genman8.svg', '#3B82F6', true, 'fill');

-- 可自定义颜色的成年女性角色 (genwoman系列)
INSERT INTO characters (id, name, height, type, media_type, media_url, thumbnail_url, color, color_customizable, color_property) VALUES
('genwoman-1', 'Generic Woman 1', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman1.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman1.svg', '#EC4899', true, 'fill'),
('genwoman-2', 'Generic Woman 2', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman2.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman2.svg', '#EC4899', true, 'fill'),
('genwoman-3', 'Generic Woman 3', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman3.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman3.svg', '#EC4899', true, 'fill'),
('genwoman-4', 'Generic Woman 4', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman4.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman4.svg', '#EC4899', true, 'fill'),
('genwoman-5', 'Generic Woman 5', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman5.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman5.svg', '#EC4899', true, 'fill'),
('genwoman-6', 'Generic Woman 6', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman6.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman6.svg', '#EC4899', true, 'fill'),
('genwoman-7', 'Generic Woman 7', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman7.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman7.svg', '#EC4899', true, 'fill'),
('genwoman-8', 'Generic Woman 8', 1.62, 'generic', 'svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman8.svg', 'https://raw.githubusercontent.com/happydrew/compareheights-characters/refs/heads/main/generic/genwoman8.svg', '#EC4899', true, 'fill');

-- 检查插入结果
SELECT 
    type, 
    COUNT(*) as count,
    AVG(height) as avg_height,
    MIN(height) as min_height,
    MAX(height) as max_height
FROM characters 
WHERE type = 'generic'
GROUP BY type;

-- 显示所有generic角色
SELECT id, name, height, color_customizable FROM characters WHERE type = 'generic' ORDER BY height, name;